Sprint2/step2
AntonSushilov/stellar_burger_react pull request #7
Opened 2023-03-28 07:55 UTC by AntonSushilov

2023-03-28 10:59 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа:
Что понравилось:
- Редьюсеры чистые функции
- Хорошо работает `Dnd`
- Хороший `codestyle` 

Что необходимо исправить:
- Необходимо подключить redux devtools - пожалуйста посмотрите как написано в тех задании.
- У вас в экшенах где нет асинхронных операций используется `dispatch`  - это ошибка. Нужно просто возвращать объект с типом экшена и `payload`

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-28 10:59 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      ingredientsData: store.ingredientsReducer.ingredients,
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-28 10:59 UTC, andryxxa93 commented on src/services/BurgerConstructor/action.js
> +export function deleteIngredientConstructor(key) {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-03-29 08:02 UTC, AntonSushilov commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      ingredientsData: store.ingredientsReducer.ingredients,
Да, я понял. Забыл объединить useSelector'ы

2023-03-29 08:02 UTC, AntonSushilov commented on src/services/BurgerConstructor/action.js
> +export function deleteIngredientConstructor(key) {
Исправил.

2023-03-29 10:17 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-11 19:33 UTC, merged