Sprint3/step1
AntonSushilov/stellar_burger_react pull request #8
Opened 2023-04-17 22:09 UTC by AntonSushilov

Не судите строго. Но почему то кажется я что то не доделал....

2023-04-18 05:39 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть механизм обновления токена
- После регистрации юзер автоматически авторизуется 
- Использовался тег `form`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный юзер не должен иметь возможность сделать заказ
- После успешного прохождения запроса на регистрацию необходимо перенаправлять юзера на главную страницу. 
- По заданию в случае успешной отправки запроса восстановления пароля пользователь должен перенаправляться на маршрут `/reset-password`, сейчас этого не происходит, пользователь так и остается на странице `/forgot-password`
- Функцию `fetchWithRefresh` необходимо использовать только с запросами, которые имеют в опциях `accessToken` токен.

- Обновление токена в случае ошибки работает, но не до конца. Следующий после обновления запрос уходит по адресу `http://localhost:3000/auth/user`.

 <img width="1440" alt="Снимок экрана 2023-04-18 в 08 28 25" src="https://user-images.githubusercontent.com/60173362/232679602-f7280434-fade-49b9-a4d4-0507656cb237.png">

- Не у всех компонентов с пропсами есть `propTypes`
- Если есть инпуты, то они должны быть внутри тега `form`, и на этот тег `form` нужно навешивать обработчик `onSubmit`, а не обработчик `onClick` на кнопку сабмита. Сейчас у вас не везде `form` используется.

**Можно лучше**
- После авторизации не стоит выводить в консоль имя и пароль юзера.
- Если в форме изменения данных юзера изменить изначальный пароль, то он уходит в запрос в формате - *****. 
<img width="1440" alt="Снимок экрана 2023-04-18 в 08 25 40" src="https://user-images.githubusercontent.com/60173362/232679127-3b7a95ed-960a-472e-bdad-87e8f0fe0d55.png">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-18 05:39 UTC, andryxxa93 commented on src/components/App/App.jsx
> +          <Route path="/register" element={<RegisterPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-18 05:39 UTC, andryxxa93 commented on src/components/App/App.jsx
> +            />
**Можно лучше**
Этот роут должен быть в верхней части с остальными - у него нет функционала как у модалки с ингредиентами

2023-04-18 05:39 UTC, andryxxa93 commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +const ProtectedRoute = ({ onlyUnAuth = false, component }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-04-18 05:39 UTC, andryxxa93 commented on src/pages/RegisterPage/RegisterPage.jsx
> +          <p className="text text_type_main-medium">Регистрация</p>
**Необходимо исправить**
Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.

2023-04-18 07:40 UTC, AntonSushilov commented on src/components/App/App.jsx
> +          <Route path="/register" element={<RegisterPage />} />
Немного не понял. если в роуте есть составной элемент по типу `element={<OnlyUnAuth component={<LoginPage />} />}`, то в отдельную константу записать `const route = <OnlyUnAuth component={<LoginPage />` и использовать `element={route}`?

2023-04-18 08:02 UTC, AntonSushilov commented on src/components/App/App.jsx
> +            />
Тогда мне нужно обрабатывать, если не выбраны ингредиенты. Как правильно это сделать?
Пока заглушку написал через `useNavigate`

2023-04-18 08:03 UTC, AntonSushilov commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +const ProtectedRoute = ({ onlyUnAuth = false, component }) => {
Написал

2023-04-18 08:03 UTC, AntonSushilov commented on src/pages/RegisterPage/RegisterPage.jsx
> +          <p className="text text_type_main-medium">Регистрация</p>
Исправил

2023-04-19 05:34 UTC, andryxxa93 commented on src/components/App/App.jsx
> +          <Route path="/register" element={<RegisterPage />} />
Имелось в виду записывать строки в константы - `const REGISTER_PATH = "/register"`

2023-04-19 05:38 UTC, andryxxa93 commented on src/components/App/App.jsx
> +            />
А тут не нужно создавать отдельный роут для модалки. Такого в задании нет.

2023-04-19 05:40 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-21 12:40 UTC, merged